AnimalsBucket:
  Type: AWS::S3::Bucket
  Properties:
    BucketName: ${self:custom.AnimalsBucket.name}

AnimalsBucketPolicy:
  Type: AWS::S3::BucketPolicy
  Properties:
    Bucket: !Ref AnimalsBucket
    PolicyDocument:
      Statement:
        - Sid: PublicRead
          Effect: Allow
          Principal: '*'
          Action:
            - s3:GetObject
          Resource: arn:aws:s3:::${self:custom.AnimalsBucket.name}/*